#+TITLE: Questionnaire
#+AUTHOR: AsmArtisan256
#+DATE: 13-01-2021

#+OPTIONS: html-style:nil
#+OPTIONS: html-scripts:nil

#+OPTIONS: author:nil
#+OPTIONS: email:nil
#+OPTIONS: date:t
#+OPTIONS: toc:nil

#+PROPERTY: header-args :eval no

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/style.css"/>

#+EXPORT_FILE_NAME: questionnaire

#+BEGIN_EXPORT html
<p class="spacing-64" \>
#+END_EXPORT

#+TOC: headlines 2

#+BEGIN_EXPORT html
<p class="spacing-64" \>
#+END_EXPORT


Honestly, this is more a tutorial than a challenge. It's supposed to teach
something about binaries and binary exploitation. Start the instance, connect
through =telnet= or =netcat=, and just answer the questions:

1. The information is in the output before the question;
2. Same as above;
3. Same as above;
4. Same as above;
5. The information is in the new output before the question;
6. Same as above;
7. Same as above;
8. The information is in the =test.c= file from the challenge, or the code output.
9. This is a test you can do using the binary from the downloaded files. Recommended! Your answer is dependent on the length of your input.
10. Use a tool like =objdump= to get the answer.

After all these questions, you'll get the flag, and, hopefully, learned
something about binary exploitation!


* FOOTER                                                                                              :ignore:
:PROPERTIES:
:clearpage: t
:END:
#+BEGIN_EXPORT html
<hr>
<footer>
  <div class="container">
    <ul class="menu-list">
      <li class="menu-list-item flex-basis-100-margin fit-content">
        <a href="/index.html">Home</a>
      </li>
      <li class="menu-list-item flex-basis-100-margin fit-content">
        <a href="/articles/articles.html">Articles</a>
      </li>
      <li class="menu-list-item flex-basis-100-margin fit-content">
        <a href="/writeups/htb/index.html">Write-Ups</a>
      </li>
      <li class="menu-list-item flex-basis-100-margin fit-content">
        <a class="inactive-link">13-01-2021</a>
      </li>
    </ul>
  </div>
</footer>
#+END_EXPORT
